#!/usr/bin/env ruby

begin
  require 'bundler/setup'
rescue SystemExit
  system("rbenv exec bundle install")
  Gem.clear_paths
end

dir = File.dirname(__FILE__)
INPUT_FILE = File.join(dir, 'boxen-slides.adoc')
OUTPUT_FILE = File.join(dir, 'boxen-slides.html')
TEMPLATE_DIR = File.join(dir, 'asciidoctor-backends')
IMAGES_DIR = File.join(dir, 'images')
CUSTOMCSS_FILE = File.join(dir, 'customcss.css')
FONTAWESOME_FILE = File.join(dir, 'font-awesome.css')

require 'thor'

class MyThorCommand < Thor
  require 'asciidoctor'

  desc "generate", "Generate the slide deck from #{INPUT_FILE} to #{OUTPUT_FILE}"
  def generate
    doc = Asciidoctor::load_file(INPUT_FILE,
      :template_dirs => [TEMPLATE_DIR],
      :template_engine => 'haml',
      :header_footer => true,
      :safe => Asciidoctor::SafeMode::UNSAFE,
      :attributes => {
        'iconfont-cdn' => 'http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css',
        # 'iconfont-cdn' => FONTAWESOME_FILE,
        'customcss' => CUSTOMCSS_FILE,
        'imagesdir' => IMAGES_DIR,
      }
    )

    File.open(OUTPUT_FILE, 'w+') do |file|
      file.puts doc.render
    end
  end
end

MyThorCommand.start
